# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: TestRunnerPlatform

# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '3'

configValidationMode: error

provider:
    name: aws
    region: eu-west-1
    stage: ${opt:stage, 'local'}
    runtime: nodejs20.x
    timeout: 300
    iam:
        role: arn:aws:iam::750019508495:role/AWSAPI
    environment: ${file(./serverless-env.yml):${self:provider.stage}}

package:
    patterns:
        - '!downloads/**'
        - 'downloads/.keep'
        - '!samples/**'
        - '!reports/**'
        - 'reports/.keep'
        - '!apps/**'
        - 'cmd/**'

functions:
    RunTest:
        handler: src/handlers/run-test.run
        reservedConcurrency: 1
        memorySize: 2048
        events:
            - sqs:
                  arn: arn:aws:sqs:eu-west-1:750019508495:TestRunner
                  batchSize: 1

custom:
    serverless-offline:
        noAuth: true
