# This workflow will create a docker and push it to AWS ECR

name: Deploy App to prod ecr

on:
    workflow_dispatch:

    push:
        branches:
            - 'main'
        paths:
            - '**.js'
            - 'Dockerfile'

jobs:
    deploy-ecr:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - run: npm ci

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET }}
                  aws-region: eu-west-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push image to Amazon ECR
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO}}
              run: |
                  GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
                  GIT_BRANCH=${GITHUB_REF#refs/heads/}
                  DOCKER_TAG=$GIT_BRANCH.$GIT_HASH
                  echo "REGISTRY $ECR_REGISTRY - REPO $ECR_REPOSITORY  TAG $DOCKER_TAG"
                  echo "command: docker build --build-arg AM_VERSION=$GIT_HASH -t $ECR_REPOSITORY ."
                  docker build --build-arg AM_VERSION=$GIT_HASH -t $ECR_REPOSITORY .
                  echo "command: docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG"
                  docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG
                  echo "command: docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:latest"
                  docker tag $ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:latest
                  echo "command: docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG"
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DOCKER_TAG
                  echo "command: docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest"
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
